### ISSUE TITLE
Add loading state support to buttons

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1873]
There is ongoing discussion in our WordPress project of the need for an intermediate/indeterminate state for a button that may need a moment to take effect.

I provided a simple mockup of what that loading state could be like: https://codepen.io/tylersticka/pen/NWyQPVq

It seems like we should make this a supported state for our buttons?

**Comment by gerardo-rodriguez** [comment]
Regarding disabled buttons, we may want to handle both an actual disabled state (using the `disabled` attribute) as well as a visually disabled state (no `disabled` attribute, but "disabled" CSS is applied). 👍 

This should allow for a more flexible disabled pattern so that we can have options for how to best create a more inclusive UX during implementation. 😉 

- https://css-tricks.com/making-disabled-buttons-more-inclusive/
- https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/#the-downsides-of-disabled-buttons
- https://twitter.com/housecor/status/1540054866420289539
- https://twitter.com/housecor/status/1540057313838567426

**Comment by tylersticka** [comment]
Agreed. My spinner concept would work whether the button was `disabled` or not.
