### ISSUE TITLE
Is it expected for th and td to have different alignment?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1978]
On the `/portland-device-lab` page, I noticed the table headings and table data have different alignments. `th` content is centered while `td` content is left-aligned. Is that expected?

https://c4dev.wpengine.com/portland-device-lab/

<img width="1392" alt="Screen Shot 2022-07-26 at 12 23 24 PM" src="https://user-images.githubusercontent.com/459757/181094966-fb1f324a-26e2-49ab-be0b-3e9b34403603.png">

**Comment by tylersticka** [comment]
This appears to be a content issue: The page either needs to specify `c-table` or use the WordPress Table block.

We don't enforce very opinionated table styles by default because we want to encourage their use for semantically appropriate elements without having to override a lot of opinionated styles.
