### ISSUE TITLE
Tota11y doesn't work on sandbox pages

### ISSUE THREAD

**Issue by saralohr** [cloudfour/cloudfour.com-patterns#231]
Not a huge deal, but it's a convenient tool. The icon is fixed to the bottom of the page content, rather than the viewport, and it doesn't do anything when clicked.

**Comment by tylersticka** [comment]
@saralohr I can't figure out why this would be, so it may be more appropriate to create an issue on the project's repo with a link to one of our Pattern Library pages where the bookmarklet fails: https://github.com/Khan/tota11y

We've had some Twitter interactions with the folks behind the project and they seem really nice.

**Comment by tylersticka** [comment]
It looks like this has to do with our use of `will-change: transform` on `body`. If I disable that, it works fine.

Unfortunately, I'm not sure how to resolve. One potential option would be to only apply `will-change` when the menu or toggle is hidden/shown, since the `body` likely _won't_ change if the toggle isn't even present.

cc @erikjung

**Comment by tylersticka** [comment]
The tota11y UI hasn't been updated since 2015. I've abandoned it in favor of [aXe](http://www.deque.com/products/axe/). I'm gonna close this because I don't think we should change our CSS to suit the tool.
