### ISSUE TITLE
Add `:active` styles for "Basic Button"

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#379]
The "[Basic Button](http://cloudfour-patterns.netlify.com/patterns/components/button.html#basic-button)" should have an `:active` style. See conversation [in Slack](https://cloudfour.slack.com/archives/cloudfour-pwa/p1479511782000121).

This should be similar to the "[positive](https://github.com/cloudfour/cloudfour.com-patterns/blob/master/src/assets/toolkit/styles/components/button.css#L211-L213)" `:active` state, as an example.

**Comment by gerardo-rodriguez** [comment]
The basic `Button` class uses `currentColor` for the `border-color`. This makes it a challenge. See https://github.com/postcss/postcss-color-function#can-you-support-currentcolor-so-we-can-do-colorcurrentcolor-adjuster

**Comment by tylersticka** [comment]
`<thoughts>`

- If possible, I'd prefer the basic button _not_ have very specific pseudo state rules, unless those can safely cascade to every modifier. Otherwise it's going to be a specificity issue.
- With that in mind, the current `:hover` style is inherited from the link (`a`) style. So it would make more sense to add an `:active` color to default links, rather than graft an `:active` style onto the basic button.
- Alternatively, you could create a button modifier like `.Button--link` that you could explicitly style in the desired way.
- Also... should these be anchors? I notice they all do `href="#"`, which is a telltale sign that these are actually `<button>` elements in disguise. If they don't have a destination, they're probably not links. And if they should really be buttons, then you'll probably _need_ a new modifier to achieve what you're going for.

`</thoughts>`

**Comment by gerardo-rodriguez** [comment]
> If possible, I'd prefer the basic button not have very specific pseudo state rules, unless those can safely cascade to every modifier. Otherwise we'll end up overriding it for every modifier, and colliding with it anytime we want the button to inherit its parent style.

Agree.

> Alternatively, you could create a button modifier like .Button--link that you could explicitly style in the desired way.

Yes, I was thinking this should probably be a modifier instead on my drive.

> Also... should these be anchors? I notice they all do href="#", which is a telltale sign that these are actually <button> elements in disguise. If they don't have a destination, they're probably not links. And if they should really be buttons, then you'll probably need a new modifier to achieve what you're going for.

Yep, good call. This also points to the idea that it should be a new button modifier.

Thanks for sharing your thoughts @tylersticka!
