### ISSUE TITLE
Chore: Remove `home-animation.js` unused imports

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#443]
The following GSAP packages are imported but not used in `scripts/home-animation.js`:
- `EasePack`
- `CSSPlugin`
- `AttrPlugin`

![Screen Shot 2019-05-25 at 12 37 32 PM](https://user-images.githubusercontent.com/459757/58373885-e2db1880-7ee9-11e9-9a13-60693f29705b.png)

https://github.com/cloudfour/cloudfour.com-patterns/blob/eb7c886e5b88ec8f52544cf0f199ee4975958744/src/assets/toolkit/scripts/home-animation.js#L10-L12

**Comment by tylersticka** [comment]
This is complicated.

If you remove those, the script will break. This is because GSAP at that time was still built on the assumption that certain packages would be globally available. The hack to get around this was to import them up front, as in the days before tree-shaking this was enough to make them available.

Newer versions of GSAP are structured differently, though some of these issues still remain: https://greensock.com/docs/NPMUsage

Also, it's worth noting that `scripts/home-animation.js` is never imported into a page directly. Instead it must be manually re-integrated with the SVG asset. See #334 for more info.
