### ISSUE TITLE
Define class naming convention

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#466]
The current iteration of our pattern library uses [SUIT CSS](https://suitcss.github.io/) for class names. We like SUIT because:

- The components are independent of one another and easy to install as needed.
- The class naming convention was easier to grasp for our customers, who found double punctuation in traditional BEM off-putting.
- The distinction between utility classes and non-utilities (`u-`) felt useful.
- The percentage based sizing classes felt in alignment with our ways of thinking about things.

Having used the convention across multiple projects in the last four years, we've encountered some issues with it:

- The distinction between descendant (`Parent-child`) and modifier (`Parent--modifier`) is sometimes too subtle.
- The breakpoint prefixing strategy for utilities (`u-md-size1of2`) has no equivalent for modifiers.
- Camel-case utilities are a bit less readable since they lack any segments after the prefix: `u-flexAlignContentBetween` versus `flex-align-content-between`
- We end up customizing components enough that I sometimes question their helpfulness once a project is far enough along.

With that in mind, here are some questions I'm interested in answering...

- [ ] Should we stick with SUIT-style (`ComponentName-child`) or BEM-style (`component-name__child`) formatting? (I go back and forth.)
- [ ] Should we stick with SUIT-style breakpoint prefixing (`u-md-textGrow1`) or use [BEMIT suffixes](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/) (`u-textGrow1@md`) (I think this would be a positive change.)
- [ ] For classes that include steps (such as modular scale utilities), can we switch from a leading `0` for negative steps (`text-grow-01`) to the character `n` (`text-grow-n1`)? (I say yes!)

---

@cloudfour/design @cloudfour/dev

**Comment by tylersticka** [comment]
Also ~dragging @spaceninja down with me~ assigning @spaceninja since I know [he cares about this stuff](https://spaceninja.com/2018/09/18/what-is-modular-css/).

**Comment by spaceninja** [comment]
BWAHAHAHA YOU FOOLS SHOULD NEVER HAVE INVITED ME IN YOU'LL REGRET THE DAY YOU ASKED SCOTT FOR HIS OPINIONS ON CLASS NAMES!!!

Just kidding.

My primary concern when it comes to class naming conventions is that we _have a convention_. Whether we use SUIT or BEM is not crazy important to me. I personally prefer BEM over SUIT, but I will happily go with the overall decision the team makes.

That said, since I was tagged in, let me make a few points in favor of BEM:

1. **BEM is incredibly widely used.** I don't have any stats on whether BEM is more popular than SUIT, other than anecdotal evidence from my time in the industry, but I can tell you that Cloud Four is the first place I've ever worked that uses it. CSS Tricks has 7 articles under the BEM tag, and no SUIT tag. None of that _means_ anything, except perhaps that if we use BEM standards, other devs who need to work with our code are more likely to be familiar with it than SUIT.

2. **BEM's naming convention is readable.** It is clear at a glance the difference between modifiers (`pattern--modifier`) and children (`pattern__child`). It takes a little while to get used to the double hyphens and underscores, but once you do, there's a lot of value in being able to tell at a glance that `mega-menu--new-wave` is the "new wave" variant of the Mega Menu, while `mega-menu__submenu-header` is the header element for the submenus in the Mega Menu. (Note also that the double hyphens and double underscores leaves you free to use hyphens to make the rest of the class name more readable!)

3. **BEM doesn't prevent us from using utility classes.** Every project I've worked on that uses a BEM naming convention also has utility classes. It's not a problem to keep using utilities the way we like, and reserve BEM naming for components.

4. **[BEMIT](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/) is a logical set of extensions for BEM**, from Harry "CSS Wizardry" Roberts, who I would follow into hell. If he advocates for it, I give it a _lot_ of credibility.

So, those are a few points in favor of BEM. But like I said, I'm not a zealot about it. If the team decides that SUIT works better for us, I'm happy. The important part is that we have a standard that the team agrees on, and can be supported by linting.

Tyler, thanks for starting the discussion, and for tagging me in. :)

## Resources
I've got [a lot of BEM bookmarks](https://pinboard.in/u:spaceninja/t:bem/). Here are a few of the most useful:

- [BEM 101](https://css-tricks.com/bem-101/) - CSS Tricks
- [MindBEMding – getting your head ’round BEM syntax](https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) - Harry Roberts
- [BEMIT: Taking the BEM Naming Convention a Step Further](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/) - Harry Roberts
- [Nesting Components](http://simurai.com/blog/2015/05/11/nesting-components) - Simurai
- [Battling BEM CSS: 10 Common Problems And How To Avoid Them](https://www.smashingmagazine.com/2016/06/battling-bem-extended-edition-common-problems-and-how-to-avoid-them/) - Smashing Mag

**Comment by tylersticka** [comment]
Thank you, @spaceninja! I'd love to hear if anyone in @cloudfour/design has opinions on this?

**Comment by Paul-Hebert** [comment]
As someone who straddles the line between @cloudfour/design and @cloudfour/dev I don't have a strong preference but agree with all of Scott's points about BEM. I'd lean slightly towards BEM but am also curious what other @cloudfour/design members think.

**Comment by tylersticka** [comment]
Here's where I'm at after re-reading this thread:

- I think we should use BEM. I like Suit, but the formatting problem it solved (fewer underscores) was from _outside_ our team. The formatting problem it introduces (elements being less distinct from modifiers) came up _within_ our team.
- I think we should embrace BEMIT-style suffixes for breakpoints. They are more intuitive to read and offer more clarity on how to _write_ in a wider variety of contexts.
- I think we should also embrace [ITCSS-style namespaces](https://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/). I find Suit's `u-` namespace useful, but ITCSS defines others as well. I read that article again and went from skeptical to convinced.
- I think we should switch from leading `0` for negative steps to a leading `n`.

To think about what this _means_, here's a before and after on some of our current class names (which may not actually carry over 1:1, but just as a point of reference):

Current | Proposed 
--- | --- 
`CmsContent` | `s-cms-content`
`FlexEmbed-content` | `o-flex-embed__content`
`WorkImage--tilt` | `c-work-image--tilt`
`u-md-spaceLeft03` | `u-space-left-n3@md`

What do we think? More readable? Less readable? Are the namespaces necessary or just noise?

**Comment by aileenjeffries** [comment]
I'm cool with BEM, especially the part about modifiers being obviously different than a parent-child pair.

**Comment by Josh68** [comment]
I was starting to use BEM and looking at namespaces before I came to Cloud Four. It was the main conventions-based approach that made sense to me, at the time. Overall, I'm fine with whatever folks come to consensus on, as long as it promotes standards.

**Comment by derekshirk** [comment]
I agree with @spaceninja when he shared: 

> My primary concern when it comes to class naming conventions is that we have a convention. 

Furthermore: 

- I support the transitions to BEM
- I am familiar with ITCSS-style namespaces but have little real world experience with it beyond our existing utility class prefix. 
- I am a big fan of clear suffix indicators for breakpoint specific selectors such as `@md` and `@xxl`

**Comment by gerardo-rodriguez** [comment]
> Here's where I'm at after re-reading this thread:
> 
> * I think we should use BEM. I like Suit, but the formatting problem it solved (fewer underscores) was from _outside_ our team. The formatting problem it introduces (elements being less distinct from modifiers) came up _within_ our team.
> * I think we should embrace BEMIT-style suffixes for breakpoints. They are more intuitive to read and offer more clarity on how to _write_ in a wider variety of contexts.
> * I think we should also embrace [ITCSS-style namespaces](https://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/). I find Suit's `u-` namespace useful, but ITCSS defines others as well. I read that article again and went from skeptical to convinced.
> * I think we should switch from leading `0` for negative steps to a leading `n`.
> 
> To think about what this _means_, here's a before and after on some of our current class names (which may not actually carry over 1:1, but just as a point of reference):
> 
> Current	Proposed
> `CmsContent`	`s-cms-content`
> `FlexEmbed-content`	`o-flex-embed__content`
> `WorkImage--tilt`	`c-work-image--tilt`
> `u-md-spaceLeft03`	`u-space-left-n3@md`
> What do we think? More readable? Less readable? Are the namespaces necessary or just noise?

:shipit:

**Comment by tylersticka** [comment]
We have a majority! Calling this decided. We'll enforce these conventions as part of #497. Thanks, everyone!
