### ISSUE TITLE
Site footer pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#480]
Create a footer pattern to be used throughout the site.

<img width="1425" alt="site footer" src="https://user-images.githubusercontent.com/42841342/74989500-56687280-53f5-11ea-92df-ec98d9e48cf8.png">

**Comment by tylersticka** [comment]
Markup for this already exists: https://v-next--cloudfour-patterns.netlify.app/?path=/story/components-ground-nav--cloud-four

(Note the variations for both cloudfour.com and PWA Stats.)

The goal isn't necessarily to redesign this from scratch, but we should take opportunities to improve or streamline.

Some initial thoughts:

- Can we use [CSS Grid Layout](https://gridbyexample.com/) and fall back to a less ambitious design when it isn't supported? Right now we're using some absolute positioning and other funky techniques, I bet that can be simplified... and if that technique suggests an improved or more sophisticated composition, then great!
- The links before had some contrast issues, I don't think that will be the case with our new color palette but we should keep an eye on it.
- Facebook icon, blecchhh! No thank you!

Oh, also: I think this work should include the CTA at the bottom (with the trees, etc. above). So that's something to keep in mind as well!
