### ISSUE TITLE
Thumbnail patterns

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#494]
We have several different styles of thumbnails, some are within a contained shape and some have borders. These may need to be different patterns, especially the calendar.

<img width="615" alt="Thumbnails" src="https://user-images.githubusercontent.com/42841342/75062496-c2031c00-5497-11ea-968f-ef2fbfe19bac.png">

**Comment by Paul-Hebert** [comment]
I wonder how/if this overlaps with the media object pattern?

https://github.com/cloudfour/cloudfour.com-patterns/issues/474

**Comment by tylersticka** [comment]
It very well may!

And do these overlap with #477?

These inventory issues are starting points. I've been taking the strategy of hoarding the ones I see as overlapping or related, and either creating a larger issue encompassing them, or just tackling all three in a WIP component.

Something we haven't tried yet (but works fine in my local testing) is prototyping in Storybook, so that's an approach we could take to some of these as well!

**Comment by tylersticka** [comment]
## Tasks

- [x] Embed
- [x] Rounded
- [x] Circle
- [ ] Date
