### ISSUE TITLE
CSS linting

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#497]
We should add a Stylelint config to this project.

- [x] Install [stylelint-config-cloudfour](https://github.com/cloudfour/stylelint-config-cloudfour)
- [x] Lint selectors based on the outcomes of #466

**Comment by spaceninja** [comment]
Note: Our Stylelint config hasn't really been touched since I set up the repo a year ago — let's 100% plug it in, but let's also pay attention to the pain points, so we can update the config to work better for us:

- As Tyler mentioned, we'll need to update the class naming enforcement from SUIT to BEM-style
- Are there any rules that you find yourself having to constantly disable? Maybe we should remove them!
- Are there any rules that you wish we were enforcing? Maybe we should add them!

**Comment by tylersticka** [comment]
I broke the last to-do into its own issue: #517
