### ISSUE TITLE
Add JS for expanding text input

### ISSUE THREAD

**Issue by calebeby** [cloudfour/cloudfour.com-patterns#683]
Context: https://github.com/cloudfour/cloudfour.com-patterns/issues/653#issuecomment-619286047

- Create textarea js file(s), copying the functionality of https://github.com/cloudfour/cloudfour.com-patterns/blob/master/src/assets/toolkit/scripts/lib/component/elastic-textarea.js
- ~Write tests in Jest or Cypress with testing-library (and set up these tools as necessary)~
- Make sure that built JS correctly exports the new code

**Comment by tylersticka** [comment]
> Write tests in Jest or Cypress with testing-library (and set up these tools as necessary)

We should consider carving this off into a separate issue.

**Comment by spaceninja** [comment]
Digging into this issue has exposed some questions that need answering, since this is the first JS we've added to the new pattern library. You can see the backchat in slack here, but after discussing with Caleb, here's my summary of what he was expecting for the pattern library JS:

1. All JavaScript in the Pattern Library will be TypeScript in `.ts` files.

1. The old pattern library JS used JS Classes, and we want to replace those with functions.

1. We do not want a `toolkit.js`-style top-level file as part of the npm pattern library package. There will still be one big module file from our build process, but the user can import individual functions from it.

1. That means that the usage instructions for the pattern library will not be Bootstrap-style “add this CSS class to opt into behavior”, it will need to describe how to apply the behavior function to an element.

1. In the Storybook app (which is effectively a pattern library consumer, but it consumes the raw files instead of the compiled versions) we will need to apply the functions to elements ourselves, perhaps in `preview.js`, perhaps in a `toolkit.js`-style file that we import into `preview.js`, or perhaps individually on a per-story basis.

I'm posting this summary here to gather feedback before I go too far down this route, especially from @tylersticka, @gerardo-rodriguez, and @Paul-Hebert.

**Comment by Paul-Hebert** [comment]
That all makes sense to me. A couple thoughts related to point 5:

- I think @tylersticka mentioned this but we should consider how to make sure all of our JS plays together nicely.
- I know Storybook has some issues with reloading duplicate CSS when switching stories. I wonder if there will be similar issues with JS?
- I could see having a `toolkit.js` type file in storybook that isn't exported from the package.

**Comment by gerardo-rodriguez** [comment]
1. 👍 
2. 👍 
3. 👍 
4. 👍 
5. 👍

**Comment by calebeby** [comment]
It would be nice to be able to make the "view code" button show the JS required to initialize the components, but I'm not familiar enough with storybook to know if that is possible for non-{react, vue, etc} components

**Comment by tylersticka** [comment]
> It would be nice to be able to make the "view code" button show the JS required to initialize the components, but I'm not familiar enough with storybook to know if that is possible for non-{react, vue, etc} components

This will be straightforward to add in Storybook 6. See https://github.com/storybookjs/storybook/issues/7479
