### ISSUE TITLE
Reevaluate Twig include path strategies

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#740]
We use [Twig](https://twig.symfony.com/) templates for this project because they're well supported across various platforms, and specifically in [Timber](https://www.upstatement.com/timber/), which we've enjoyed using on several WordPress projects.

Twig templates can include _other_ Twig templates in a handful of ways:

```twig
{# Output a template right here #}
{% include 'template.twig' %}

{# As a function #}
{{include('template.twig')}}
{# or #}
{% set content = include('template.twig') %}
{{content}}

{# Override layout blocks within #}
{% embed 'template.twig' %}
  {% block title %}
    <h2>Hello world!</h2>
  {% endblock %}
{% endembed %}
```

What all of these techniques have in common is that they require _a path to a template_. If Twig can't find `template.twig`, it can't render its contents.

And what _this_ project requires are paths that will work here not just in our Storybook examples, but _elsewhere_... specifically within our WordPress theme.

## What we do now
Our strategy so far has been to use relative paths.

So given this simplified version of our pattern repo's structure:

```
src
├── components
│   └── button
│       └── button.twig
├── objects
│   └── container
│       └── container.twig
└── prototypes
    └── example
        └── hello-world.twig
```

The paths  `hello-world.twig` would use to access the other templates look like this:

```twig
{% embed '../../objects/container/container.twig' %}
  {% block content %}
    {% include '../../components/button/button.twig' %}
  {% endblock %}
{% endembed %}
```

Because the paths are relative, they should work as long as the templates don't change location relative to each other. So in a WordPress project structured like this:

```
wp-content
└── themes
    └── example-theme
        ├── node_modules
        │   └── @cloudfour
        │       └── patterns
        └── templates
            └── page.twig
```

`page.twig` could reference `hello-world.twig` without issue:

```twig
{% include '../node_modules/@cloudfour/patterns/src/prototypes/example/hello-world.twig' %}
```

### Benefits of this approach
- It requires no configuration (it is the default behavior), which means it works consistently across platforms.
- It's easy to understand.
- In JavaScript, only templates that are actually referenced are loaded.

### Issues with this approach
Unfortunately, I've noticed some issues in actual use I believe we'll have to address soon.

#### Long paths
I don't know about you, but seeing paths like `../node_modules/@cloudfour/patterns/src/prototypes/example/hello-world.twig` makes me kind of sad.

#### Harder to move
Because the paths are relative, they'll change slightly depending on the depth of the file you're working in. If you decide to move a template from `templates/a.twig` to `templates/a/default.twig`, you will have to add another `../` segment to each and every include path therein.

They'll also change depending on the platform, which is likely to have a different directory structure. We've talked about leveraging future Storybook source improvements to expose more code samples, but those will be of limited utility if you the paths won't work in your project.

#### Lack of dynamic paths in JavaScript
When our projects have an absolute directory of includes or partials, it lets us write components that can extend different paths based on a property.

Consider the social media links in our website footer:

<img width="302" alt="Screen Shot 2020-05-22 at 4 24 44 PM" src="https://user-images.githubusercontent.com/69633/82927484-a21b4280-9f35-11ea-99c4-f71e8e15fbdb.png">

Ideally, those links would be defined in our CMS. So our template for outputting them might look like this:

```twig
<ul>
  {% for item in menu.items %}
    <a href="{{item.link}}">
      {% include ['../path/to/' ~ item.slug ~ '.svg.twig', '../path/to/fallback.svg.twig'] with { class: 'c-icon' } only %}
      <span class="u-hidden-visually">{{item.name}}</span>
    </a>
  {% endfor %}
</ul>
```

This would work fine in PHP: If the item's slug matches an icon key, it will display, otherwise the fallback will display.

But in client-side JavaScript the slug will _never_ match. That's because relative include paths are fetched prior to compilation, _not_ prior to render. Since Twig can't know the path until the template is rendered with data, it won't have fetched that file.

#### Misc. "inline template" errors in JavaScript
While writing the complex Sky Nav component, I encountered issues where attempting to keep my code DRY with separate templates resulted in seemingly random errors complaining that certain template types were not allowed to be inline. The issues I found related to this pointed either to a missing configuration option (which our project already sets) and to relative paths.

## Alternative 1: Use a different Twig
Our project currently uses [Twig.js](https://github.com/twigjs/twig.js/wiki) and [twig-loader](https://github.com/zimmo-be/twig-loader). There is a competing Twig implementation called [Twing](https://www.npmjs.com/package/twing) and a [twing-loader](https://github.com/NightlyCommit/twing-loader#readme). Twing is more complex to setup, but boasts greater parity with the PHP version of Twig. Its loader also includes a pre-compilation strategy that may solve some of the issues we've been seeing.

## Alternative 2: Register templates ahead of time
It's possible in Twig.js to [register templates at runtime](https://github.com/zimmo-be/twig-loader#dynamic-templates-and-registering-at-runtime), letting the engine know up-front what templates are available.

### Benefits of this approach
- Dynamic include paths can be evaluated as long as they match a template that was registered at runtime.
- Less chance of an "inline template" error since templates are evaluated ahead of time (rather than being injected at the time of request).
- Ability to simplify paths so they can be more concise.

### Issues with this approach
- Unlike relative paths, this approach will require configuration.
- As near as I can tell, partial paths that are preregistered will no longer be relative. So if you register a path at `components/button/button.twig`, the path will be the same no matter what folder depth you are in.
- Because this solution requires configuration, it will also require additional steps to integrate those templates in other projects. We wouldn't want to use a path format that we couldn't recreate in the PHP version of Twig, for example.

## Next steps
- Explore Alternative 1 to see if it can solve the issues we're seeing.
	- If so, proceed with a PR.
	- If not, move on to exploring Alternative 2, specifically checking if relative paths are actually supported or not.
		- If  relative paths_are_ actually supported with this strategy, proceed straight to PR.
		- If relative paths are _not_ supported, research pathing strategies that will work across JS and PHP implementations and proceed with PRs for both projects.

**Comment by calebeby** [comment]
@tylersticka Can you link to the code or documentation for how to specify pre-compilation with Twing?

**Comment by calebeby** [comment]
@tylersticka I'm also curious what your thoughts are on this:

Even if we didn't have the issue with pre-compiling/dynamic import paths, would we still want to switch to non-relative paths?

**Comment by calebeby** [comment]
If you are looking at the section in the Twing README about "Render at compile time", my gut reaction is that I don't think this will solve the problem we are having because it looks like requires you to pass in the data used to render via the loader config, but in our case, the data exists within the .mdx files, where the template functions are called.

Is there something else that Twing offers that is closer to twig-loader's pre-compile ability which still allows you to pass in the data at runtime?

**Comment by tylersticka** [comment]
> Can you link to the code or documentation for how to specify pre-compilation with Twing?

I think this is the relevant example I saw: https://github.com/NightlyCommit/twing-loader#render-at-compile-time

> Is there something else that Twing offers that is closer to twig-loader's pre-compile ability which still allows you to pass in the data at runtime?

I'm not sure, I haven't actually used it.

> Even if we didn't have the issue with pre-compiling/dynamic import paths, would we still want to switch to non-relative paths?

This is a great question! It really depends on what we want to do on the server side as well.

I know there's a PHP plugin to add namespaces: https://github.com/EvanLovely/plugin-twig-namespaces

**Comment by calebeby** [comment]
Ok, here is the approach that I think will work:

- Use `twing-loader`
- https://github.com/NightlyCommit/twing-loader#render-at-runtime: In the `environment.js`, instead of using the filesystem loader, I would use the [`TwingLoaderArray`](https://nightlycommit.github.io/twing/api.html#twingloaderarray) option which would pre-load _all_ twig files from the file-system, so that they are all in the bundle
- In PHP, https://github.com/EvanLovely/plugin-twig-namespaces lets us use import paths like `@cloudfour/patterns/components/input/input.twig`
- The same import paths would be used in JS by automatically creating those paths for each file before passing them into twingLoaderArray

I haven't tried this out yet, but it looks to me like it should work

Does this approach sound like it would solve all the problems @tylersticka?

**Comment by tylersticka** [comment]
@calebeby I think so! Thank you for digging in and doing the research.

**Comment by calebeby** [comment]
One concern that I have is that this approach might not handle automatically updating when files on disk change. So if you change a demo twig file, then storybook might not automatically rebuild with those changes. If it doesn't automatically do that, then I might need to add a custom TwigLoader to use instead of TwigLoaderArray

**Comment by tylersticka** [comment]
@calebeby Yeah, that would definitely be an issue.

**Comment by calebeby** [comment]
@tylersticka The twig namespaces plugin you linked says "for pattern lab", will that work with wordpress?

**Comment by tylersticka** [comment]
@calebeby That is an _excellent_ question. 🙃 

It looks like a plugin might not be necessary? I see support for name-spaced paths being added directly to Twig in the docs: https://twig.symfony.com/doc/3.x/api.html#built-in-loaders

It looks like the plugin may just be exposing that to Pattern Lab: https://github.com/EvanLovely/plugin-twig-namespaces/blob/master/src/PatternLab/TwigNamespaces/PatternLabListener.php#L43

Also possibly helpful, here is the Timber docs for adding options to Twig: https://timber.github.io/docs/guides/extending-timber/#adding-functionality-to-twig

**Comment by tylersticka** [comment]
(Side note: Another argument for switching to Twing is that Twig.js doesn't seem to support include path arrays _at all_.)

**Comment by calebeby** [comment]
Ok, for now I'm going to assume "setting up namespaces can be done on the wp/php side" and I'm not going to worry about exactly how that part is going to work.

I'm running into some issues with twing-loader now unfortunately. It's not allowing me to require('fs') in the environment.js file since that file gets required in node and it also gets bundled. I'm looking into options to see if that file can be dynamically generated when it is bundled

**Comment by tylersticka** [comment]
You may already have tried this, but I've had more success using `require.context` to traverse files by path when working in Webpack-land. Example: https://github.com/cloudfour/cloudfour.com-patterns/blob/v-next/src/design/icons/icons.stories.mdx#L3-L20

**Comment by calebeby** [comment]
TIL, that may come in handy!

**Comment by calebeby** [comment]
I got it working!

![image](https://user-images.githubusercontent.com/13206945/83083852-1c35ef00-a03c-11ea-9649-c0d11a9840f0.png)

I think I've never been more excited to see buttons 😂 

Auto-recompiling on change works correctly, even when you are modifying a file which is only transitively referenced

Tomorrow I will go through all the files and update the paths and comment out stuff that doesn't work with the stricter twig syntax

And I will need to update the cypress runner config so that it can pull in the twig files as well

**Comment by tylersticka** [comment]
![](http://lol.tylersticka.com/yes3.gif)
