### ISSUE TITLE
Update favicons

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#746]
Our color palette has been updated, so our icons should be updated as well. There are also new best practices for favicons we can follow.

These should also be documented in Storybook (possibly related: #725).

More info: https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/

**Comment by derekshirk** [comment]
Note to self: Review favicon additions introduced in #535

**Comment by aileenjeffries** [comment]
@tylersticka I've pushed my branch for this, `aj-favicon` and had a few questions, primarily about documentation. I kept the magenta development / blue production trick since I find it handy, so that means 4 total favicon files. I added a little section under Brand about favicons, explaining why we're stroking it in white. But, I'd love to be able to actually demonstrate the need for this by coloring the Story the icon is shown in, in something similar to Firefox's dark gray. 

My other question is more general, about how to document icons such as the MS Tile. That tile is a two parter - the png, plus a browserconfig.xml file specifying the tile's background color. I added both to the static directory, and updated `manager-head.html` but I'm not sure if this is really sufficient documentation? Same deal with the masked Android/PWA icon. I found this write up: https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/ made a new png with the icon being inside the safe zone, and then added a manifest.json because you need to add `"purpose": "maskable"`  to that icon's listing. But again, is this really the ideal documentation? Do we have other pattern libraries for clients that document this sort of stuff that isn't really a pattern but still affects the look and function of the site?

**Comment by tylersticka** [comment]
Relevant: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

**Comment by tylersticka** [comment]
The longer we wait on this, the less we need to provide (it seems): https://css-tricks.com/how-to-favicon-in-2021/
